# Generated by Django 3.2.22 on 2024-05-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240515_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('affected_brand', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1500)),
                ('malicious_url', models.URLField()),
                ('malicious_domain_registration_date', models.DateField()),
                ('malicious_domain_dns_a', models.CharField(max_length=255)),
                ('malicious_domain_dns_ns', models.CharField(max_length=255)),
                ('malicious_domain_dns_mx', models.CharField(max_length=255)),
                ('matching_keywords', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.event')),
            ],
        ),
    ]
