# Generated by Django 3.2.22 on 2024-05-15 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='malicious_domain_registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
